AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: >
  Cluno

  Full stack coding challenge solution

Globals:
  Function:
    Timeout: 3

Resources:
  ListOffersFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: dist/
      Handler: handlers.listOffers
      Runtime: nodejs12.x
      Events:
        ListOffers:
          Type: Api
          Properties:
            Path: /offers
            Method: get

  OfferDetailsFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: dist/
      Handler: handlers.offerDetails
      Runtime: nodejs12.x
      Events:
        ListOffers:
          Type: Api
          Properties:
            Path: /offers/{id}
            Method: get
